# Generated by Django 4.1.7 on 2023-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
