# Generated by Django 4.1.7 on 2023-04-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Year_of_leaving',
            new_name='Date_of_leaving',
        ),
    ]
