# Generated by Django 4.1.7 on 2023-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_year_of_leaving_student_date_of_leaving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Date_of_leaving',
        ),
        migrations.AddField(
            model_name='student',
            name='Year_of_leaving',
            field=models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], null=True, verbose_name='Year_of_leaving'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_status',
            field=models.CharField(choices=[('Terminated', 'Terminated'), ('Completed', 'Completed'), ('Shifted', 'Shifted'), ('Semester Leave', 'Semester Leave')], max_length=255),
        ),
    ]
