# Generated by Django 4.1.7 on 2023-04-07 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_year_of_leaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_status',
            field=models.CharField(choices=[('Terminated', 'Terminated'), ('Completed', 'Completed'), ('Shifted', 'Shifted'), ('Semester Leave', 'Semester Leave'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year_of_leaving',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
