# Generated by Django 4.1.7 on 2023-04-07 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_student_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Date_of_joining',
            new_name='Joining_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='Year_of_leaving',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2033)]),
        ),
    ]
