# Generated by Django 4.1.7 on 2023-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Contingency_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
