# Generated by Django 4.1.7 on 2023-04-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_contingency_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='Instructor_id',
            new_name='Instructor_Id',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='Student_id',
            new_name='Student_Id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email_id',
            new_name='Email_Id',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('Log_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.TextField()),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Price', models.PositiveIntegerField()),
                ('Source', models.TextField(blank=True, null=True)),
                ('Credit', models.TextField(blank=True, null=True)),
                ('Claim_amount', models.PositiveIntegerField()),
                ('Opening_balance', models.PositiveIntegerField()),
                ('Opening_balance_on_date', models.DateField()),
                ('Closing_balance', models.PositiveIntegerField()),
                ('Closing_balance_on_date', models.DateField()),
                ('Forward_by', models.TextField()),
                ('Forwarded_on_date', models.DateField()),
                ('Sanctioned_amount', models.PositiveIntegerField()),
                ('Remark', models.TextField(blank=True, null=True)),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
