# Generated by Django 4.1.7 on 2023-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='Forward_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='Source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
